### ISSUE TITLE
broken example

### ISSUE THREAD

**Issue by mr-cheffy** [gabivlj/candice#4]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x576cb4]

goroutine 1 [running]:
github.com/llir/llvm/ir.(*Func).NewBlock(...)
        /home/mauro/go/pkg/mod/github.com/llir/llvm@v0.3.4/ir/func_block.go:10
github.com/gabivlj/candice/internals/compiler.(*Compiler).compileIf(0xc0001420c0, 0xc000122850)
        /home/mauro/Downloads/candice/internals/compiler/compiler.go:639 +0xf4
github.com/gabivlj/candice/internals/compiler.(*Compiler).Compile(0xc0001420c0, {0x620008?, 0xc000122850?})
        /home/mauro/Downloads/candice/internals/compiler/compiler.go:451 +0x2e6
github.com/gabivlj/candice/internals/compiler.(*Compiler).Compile(0xc0001420c0, {0x6200d0?, 0xc000010900?})
        /home/mauro/Downloads/candice/internals/compiler/compiler.go:426 +0xe2f
github.com/gabivlj/candice/internals/compiler.(*Compiler).CompileWithEventHandler(...)
        /home/mauro/Downloads/candice/internals/compiler/compiler.go:316
github.com/gabivlj/candice/internals/build.ExecuteProject()
        /home/mauro/Downloads/candice/internals/build/builder.go:104 +0x70f
main.main()
        /home/mauro/Downloads/candice/cmd/build/main.go:7 +0x17

```

code:

```
number := 10

if number >= 5 && number <= 10
    @print("number is between 5 and 10");

if number >= 5 && number <= 10 @print("number is between 5 and 10");
else if number > 0 || number < 0 {
    @print("atleast the number is more or less than 0");
} else {
    @print("oh no! candice is broken");
    @print("please fix...");
}
```

**Comment by gabivlj** [comment]
Thanks for submitting this panic error! 
You have to wrap it in `func main() { ... }` for it to work. 

I think it's worth it adding a compiler error if certain statements are not under a function, compiler should never panic!

**Comment by gabivlj** [comment]
New changes showcases this error:
<img width="943" alt="image" src="https://github.com/gabivlj/candice/assets/24482526/c5e77d42-f210-4dec-aa37-e8de2d2e1661">

**Comment by mr-cheffy** [comment]
great work 👍🏽. Thanks you a lot
